/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_petronas_dip_Dip */

#ifndef _Included_com_petronas_dip_Dip
#define _Included_com_petronas_dip_Dip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_petronas_dip_Dip
 * Method:    run
 * Signature: ([FIIIIIFF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_petronas_dip_Dip_run
  (JNIEnv *, jclass, jfloatArray, jint, jint, jint, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
